services:
  postgres:
    image: postgres:14-alpine
    command: postgres -c 'max_connections=200'
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
networks:
  clan-local:
    driver: bridge

